//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom18WebBanHoa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBanHoaEntities : DbContext
    {
        public QuanLyBanHoaEntities()
            : base("name=QuanLyBanHoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual DbSet<Don_Hang> Don_Hang { get; set; }
        public virtual DbSet<Loai_San_Pham> Loai_San_Pham { get; set; }
        public virtual DbSet<Nguoi_Dung> Nguoi_Dung { get; set; }
        public virtual DbSet<Nguoi_Giao_Hang> Nguoi_Giao_Hang { get; set; }
        public virtual DbSet<Nha_Cung_Cap> Nha_Cung_Cap { get; set; }
        public virtual DbSet<San_Pham> San_Pham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trang_Thai> Trang_Thai { get; set; }
    }
}
