//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom18WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_Pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_Pham()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
        }
    
        public int id { get; set; }
        public string tenSP { get; set; }
        public string hinh { get; set; }
        public Nullable<double> gia { get; set; }
        public string mota { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<System.DateTime> ngaydanghinh { get; set; }
        public int idloaiSP { get; set; }
        public int idNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Loai_San_Pham Loai_San_Pham { get; set; }
        public virtual Nha_Cung_Cap Nha_Cung_Cap { get; set; }
    }
}
